apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mvcdocker
  name: mvcdocker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mvcdocker 
  template:
    metadata:
      labels:
        app: mvcdocker
    spec:
      containers:
      - image: liranp1/mvcdocker:v1.13
        name: mvcdocker
        resources: {}
        ports:
        - containerPort: 5297
        volumeMounts:
        - name: mvc-pv-claim
          mountPath: "/app/files"
      volumes:
      - name: mvc-pv-claim
        persistentVolumeClaim:
          claimName: task-pv-claim
