apiVersion: v1
kind: Pod
metadata:
  name: mvcdocker
spec:
  volumes:
  - name: mvc-pv-claim
    persistentVolumeClaim:
      claimName: mvc-pv-claim
  containers:
  - name: mvcdocker
    image: liranp1/mvcdocker:v1.12
    ports:
      - containerPort: 5297
        name: "mvcdocker"
    volumeMounts:
      - name: mvc-pv-claim
        mountPath: "/app/files"
